<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="64" started-at="2019-01-24T20:19:10Z" finished-at="2019-01-24T20:19:10Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="64" started-at="2019-01-24T20:19:10Z" finished-at="2019-01-24T20:19:10Z">
      <class name="extendsReports.Functionality1">
        <test-method status="PASS" signature="setUp()[pri:0, instance:extendsReports.Functionality1@7cbd213e]" name="setUp" is-config="true" duration-ms="323" started-at="2019-01-24T20:19:09Z" finished-at="2019-01-24T20:19:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="functionality1Test1()[pri:0, instance:extendsReports.Functionality1@7cbd213e]" name="functionality1Test1" duration-ms="10" started-at="2019-01-24T20:19:10Z" finished-at="2019-01-24T20:19:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- functionality1Test1 -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:extendsReports.Functionality1@7cbd213e]" name="getResult" is-config="true" duration-ms="9" started-at="2019-01-24T20:19:10Z" finished-at="2019-01-24T20:19:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=functionality1Test1 status=SUCCESS method=Functionality1.functionality1Test1()[pri:0, instance:extendsReports.Functionality1@7cbd213e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="FAIL" signature="functionality1Test2()[pri:0, instance:extendsReports.Functionality1@7cbd213e]" name="functionality1Test2" duration-ms="2" started-at="2019-01-24T20:19:10Z" finished-at="2019-01-24T20:19:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Sakinala] but found [Krishna]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Sakinala] but found [Krishna]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at extendsReports.Functionality1.functionality1Test2(Functionality1.java:16)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- functionality1Test2 -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:extendsReports.Functionality1@7cbd213e]" name="getResult" is-config="true" duration-ms="10" started-at="2019-01-24T20:19:10Z" finished-at="2019-01-24T20:19:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=functionality1Test2 status=FAILURE method=Functionality1.functionality1Test2()[pri:0, instance:extendsReports.Functionality1@7cbd213e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="FAIL" signature="functionality1Test3()[pri:0, instance:extendsReports.Functionality1@7cbd213e]" name="functionality1Test3" duration-ms="1" started-at="2019-01-24T20:19:10Z" finished-at="2019-01-24T20:19:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.assertNotEquals(Assert.java:1157)
at org.testng.Assert.assertNotEquals(Assert.java:1162)
at extendsReports.Functionality1.functionality1Test3(Functionality1.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- functionality1Test3 -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:extendsReports.Functionality1@7cbd213e]" name="getResult" is-config="true" duration-ms="4" started-at="2019-01-24T20:19:10Z" finished-at="2019-01-24T20:19:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=functionality1Test3 status=FAILURE method=Functionality1.functionality1Test3()[pri:0, instance:extendsReports.Functionality1@7cbd213e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:extendsReports.Functionality1@7cbd213e]" name="tearDown" is-config="true" duration-ms="325" started-at="2019-01-24T20:19:10Z" finished-at="2019-01-24T20:19:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- extendsReports.Functionality1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
